// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolDBAPI.Library.DataAccess;

namespace SchoolDBAPI.Library.Migrations
{
    [DbContext(typeof(SchoolDBContext))]
    [Migration("20201013120852_CourseIdAdded")]
    partial class CourseIdAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SchoolDBAPI.Library.Models.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSchoolEmail")
                        .HasColumnType("bit");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Emails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAddress = "203948@school.org",
                            IsSchoolEmail = true,
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            EmailAddress = "keira54@yahoo.com",
                            IsSchoolEmail = false,
                            PersonId = 2
                        },
                        new
                        {
                            Id = 3,
                            EmailAddress = "wilmer02@hane.com",
                            IsSchoolEmail = false,
                            PersonId = 3
                        },
                        new
                        {
                            Id = 4,
                            EmailAddress = "vesta.leffler@stracke.info",
                            IsSchoolEmail = false,
                            PersonId = 4
                        },
                        new
                        {
                            Id = 5,
                            EmailAddress = "kelsie.lueilwitz@gmail.com",
                            IsSchoolEmail = false,
                            PersonId = 5
                        },
                        new
                        {
                            Id = 6,
                            EmailAddress = "ressie49@bernier.com",
                            IsSchoolEmail = false,
                            PersonId = 2
                        },
                        new
                        {
                            Id = 7,
                            EmailAddress = "dkuhlman@yahoo.com",
                            IsSchoolEmail = false,
                            PersonId = 1
                        },
                        new
                        {
                            Id = 8,
                            EmailAddress = "rhoppe@gmail.com",
                            IsSchoolEmail = false,
                            PersonId = 6
                        });
                });

            modelBuilder.Entity("SchoolDBAPI.Library.Models.People.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Sam",
                            Grade = 100,
                            LastName = "Lee",
                            StudentId = 203948
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Jacey",
                            Grade = 80,
                            LastName = "Feng",
                            StudentId = 102942
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Brandon",
                            Grade = 100,
                            LastName = "Lee",
                            StudentId = 293481
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Sue",
                            Grade = 90,
                            LastName = "Jordan",
                            StudentId = 203941
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "John",
                            Grade = 80,
                            LastName = "Thomas",
                            StudentId = 920341
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Javier",
                            Grade = 80,
                            LastName = "Mcgregor",
                            StudentId = 763343
                        });
                });

            modelBuilder.Entity("SchoolDBAPI.Library.Models.People.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Crowler",
                            LastName = "Starks",
                            Salary = 44000m
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Rima",
                            LastName = "Irving",
                            Salary = 42000m
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Jack",
                            LastName = "Bonilla",
                            Salary = 43000m
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Keisha",
                            LastName = "Higgins",
                            Salary = 41200m
                        });
                });

            modelBuilder.Entity("SchoolDBAPI.Library.Models.PhoneNum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsMobile")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Owner")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PhoneNumbers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsMobile = true,
                            Number = "040690660",
                            Owner = 0,
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsMobile = false,
                            Number = "87164280",
                            Owner = 2,
                            PersonId = 2
                        },
                        new
                        {
                            Id = 3,
                            IsMobile = true,
                            Number = "048877120",
                            Owner = 1,
                            PersonId = 3
                        },
                        new
                        {
                            Id = 4,
                            IsMobile = true,
                            Number = "0406938120",
                            Owner = 0,
                            PersonId = 4
                        },
                        new
                        {
                            Id = 5,
                            IsMobile = true,
                            Number = "0406936119",
                            Owner = 3,
                            PersonId = 5
                        },
                        new
                        {
                            Id = 6,
                            IsMobile = false,
                            Number = "94104280",
                            Owner = 4,
                            PersonId = 1
                        },
                        new
                        {
                            Id = 7,
                            IsMobile = true,
                            Number = "0416928190",
                            Owner = 1,
                            PersonId = 6
                        },
                        new
                        {
                            Id = 8,
                            IsMobile = true,
                            Number = "0466138120",
                            Owner = 0,
                            PersonId = 3
                        });
                });

            modelBuilder.Entity("SchoolDBAPI.Library.Models.SchoolBusiness.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Subject")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = "M108THT",
                            Subject = 0,
                            TeacherId = 1,
                            Title = "Maths 101"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = "S238ICE",
                            Subject = 2,
                            TeacherId = 2,
                            Title = "Science 401"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = "E762LSH",
                            Subject = 1,
                            TeacherId = 3,
                            Title = "English 201"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = "H289OWJ",
                            Subject = 11,
                            TeacherId = 4,
                            Title = "Sports 101"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = "N293OAI",
                            Subject = 0,
                            TeacherId = 1,
                            Title = "Algebra 101"
                        },
                        new
                        {
                            Id = 6,
                            CourseId = "Z918OIQ",
                            Subject = 0,
                            TeacherId = 2,
                            Title = "Geometry 101"
                        },
                        new
                        {
                            Id = 7,
                            CourseId = "L009JNA",
                            Subject = 12,
                            TeacherId = 3,
                            Title = "Drama 101"
                        },
                        new
                        {
                            Id = 8,
                            CourseId = "O019PKV",
                            Subject = 2,
                            TeacherId = 4,
                            Title = "Biology 301"
                        });
                });

            modelBuilder.Entity("SchoolDBAPI.Library.Models.SchoolBusiness.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            CourseId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            EnrollmentId = 2,
                            CourseId = 1,
                            StudentId = 2
                        },
                        new
                        {
                            EnrollmentId = 3,
                            CourseId = 2,
                            StudentId = 3
                        },
                        new
                        {
                            EnrollmentId = 4,
                            CourseId = 3,
                            StudentId = 4
                        },
                        new
                        {
                            EnrollmentId = 5,
                            CourseId = 4,
                            StudentId = 1
                        },
                        new
                        {
                            EnrollmentId = 6,
                            CourseId = 2,
                            StudentId = 5
                        },
                        new
                        {
                            EnrollmentId = 7,
                            CourseId = 4,
                            StudentId = 6
                        });
                });

            modelBuilder.Entity("SchoolDBAPI.Library.Models.SchoolBusiness.Course", b =>
                {
                    b.HasOne("SchoolDBAPI.Library.Models.People.Teacher", "Teacher")
                        .WithMany("CoursesTaught")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolDBAPI.Library.Models.SchoolBusiness.Enrollment", b =>
                {
                    b.HasOne("SchoolDBAPI.Library.Models.SchoolBusiness.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolDBAPI.Library.Models.People.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
